### ISSUE TITLE
[QUESTION] 1.16.4/5 version

### ISSUE THREAD

**Issue by nullified33** [ByMartrixx/SecurityCraftFabric#1]
**Question**  Is 1.16.4 version going to be made

**Comment by IotaBread** [comment]
Sadly, I don't have plans on the near future to continue the work in this port. I do have plans to rewrite this port from scratch and to prioritize working versions with less content rather than a big release with everything ported and working, this should make the development of the port a bit faster and better. The supported versions will depend on when I start to work on the port again.
